# Generated by Django 4.2 on 2023-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_searching_game',
            field=models.BooleanField(default=False),
        ),
    ]
