# Generated by Django 4.2 on 2023-05-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_is_searching_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
        ),
    ]
