# Generated by Django 4.2 on 2023-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_game_player1'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='agora_token_player1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='agora_token_player2',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
