# Generated by Django 4.2 on 2023-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_game_agora_token_player1_game_agora_token_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='agora_token_player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='agora_token_player2',
        ),
        migrations.AddField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
