# Generated by Django 4.2 on 2023-05-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_game_agora_token_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_started',
        ),
    ]
