# Generated by Django 4.2 on 2023-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_game_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
