# Generated by Django 4.2 on 2023-05-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_game_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_bet',
            name='amount',
        ),
    ]
