# Generated by Django 4.2 on 2023-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_game_bet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_bet',
            name='game',
        ),
        migrations.AddField(
            model_name='game_bet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
