# Generated by Django 4.2 on 2023-05-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_game_is_controlled_by_site_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='random_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
