# Generated by Django 4.2 on 2023-05-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_game_random_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_bet',
            name='current_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.game'),
        ),
    ]
