# Generated by Django 4.2 on 2023-07-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payeer',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
